### ISSUE TITLE
a small dataset provided

### ISSUE THREAD

**Issue by helxsz** [ndrplz/surround_vehicles_awareness#1]
@ndrplz Thanks for the code and dataset, however the dataset is way too big for me to download, would it be ok to have a smaller dataset to train ?

**Comment by ndrplz** [comment]
@helxsz  Hi, well in theory yes, however we empirically found that the dataset size is very important in order to be able to generalize correctly. Maybe I could pack a subset of the examples in a self-contained sub-dataset, but I'm not sure that would be useful, at least for the original purpose

**Comment by ndrplz** [comment]
@helxsz Hi, from today the dataset is split into 300 smaller subset, and each one can be downloaded and uncompressed separately. To get the new download link you can fill the form on the [dataset page](http://imagelab.ing.unimore.it/imagelab/page.asp?IdPage=19).
