### ISSUE TITLE
Unable to get SVA dataset

### ISSUE THREAD

**Issue by anandsm7** [ndrplz/surround_vehicles_awareness#11]
Hi,

The aimage lab dataset link seems broken.Is there anyway to get the GTA V SVA dataset ?

Regards

**Comment by ndrplz** [comment]
Hi @anandsm7 

We just migrated to a newer webserver and there are still a few technical issues. 

Please email me your name, surname and affiliation (in private, to my institutional address) and I'll give you directly the link to the data

**Comment by SrinjaySarkar** [comment]
Hey @ndrplz , still can't download the dataset from the link in the README file.
