### ISSUE TITLE
Couldn't download  pre-trained weights

### ISSUE THREAD

**Issue by Omfff** [ndrplz/surround_vehicles_awareness#13]
When I download http://imagelab.ing.unimore.it/files/pretrained_models/keras/SPDN_w.hdf5," HTTP Error 404.3 - Not Found" occurs.

**Comment by ndrplz** [comment]
That should be back now thanks to [Federico](https://github.com/prittt) who fixed the issue

**Comment by Omfff** [comment]
@ndrplz  Thank you!
