### ISSUE TITLE
Error using theano

### ISSUE THREAD

**Issue by ervinyo** [ndrplz/surround_vehicles_awareness#14]
Hi,

Thank you for sharing your code. I am have issues about your code. 
input_crop = Input(shape=(3, 224, 224)) changed to input_crop = Input(shape=(224, 224, 3))
it can run but there is error like this
Traceback (most recent call last):
  File "main.py", line 28, in <module>
    Y_pred = model.predict([X_coords, X_crops])
  File "C:\Users\user\anaconda3\envs\py2\lib\site-packages\keras\engine\training.py", line 1166, in predict
    check_batch_dim=False)
  File "C:\Users\user\anaconda3\envs\py2\lib\site-packages\keras\engine\training.py", line 111, in standardize_input_data
    str(array.shape))
Exception: Error when checking : expected input_2 to have shape (None, 224, 224, 3) but got array with shape (1L, 3L, 224L, 224L)

Could you help me for solve this issues ? Thank you

**Comment by ndrplz** [comment]
Hi @ervinyo,

as suggested by the stacktrace, your input is channels first (i.e. the 3 channels are in second position) while the expected shape is channel last (i.e. channels in last position)

**Comment by ervinyo** [comment]
thanks for reply. I already try it but didn't understand about that. Which is part we must change in detail ? model.py, main.py or utils.py 


> Hi @ervinyo,
> 
> as suggested by the stacktrace, your input is channels first (i.e. the 3 channels are in second position) while the expected shape is channel last (i.e. channels in last position)

**Comment by ervinyo** [comment]
it is done by change C:\Users\user\.keras\keras.json to:
```
{
    "image_dim_ordering":"th",
    "floatx": "float32",
    "epsilon": 1e-07,
    "backend": "theano",
    "image_data_format": "channels_first"
}
```
and then add add this as .theanorc.txt to C:/ users/whatever
```
[global]
floatX = float32
device = cpu
optimizer = None
```
I hope can help someone. Thank you.

**Comment by ndrplz** [comment]
Good, thanks for sharing with the posterity :)
