### ISSUE TITLE
homography model

### ISSUE THREAD

**Issue by WERush** [ndrplz/surround_vehicles_awareness#3]
Hi, thanks for introducing this interesting task.

Can you share your code about your baseline method -- homography model? I want to make some comparisons. 

Thanks.

**Comment by ndrplz** [comment]
Hi @WERush,

sorry for the delay. I prepared a Gist [here](https://gist.github.com/ndrplz/ac164425c8e4d19b8a14566f497eef9b) with the code you need.

Hope it helps!

**Comment by WERush** [comment]
@ndrplz 
It is helpful. Thanks very much.
