### ISSUE TITLE
Bird-eye view data generation

### ISSUE THREAD

**Issue by AmalMak** [ndrplz/surround_vehicles_awareness#4]
Thanks for this amazing project, and keep up the good work.

Regarding the bird-eye view data generation, is it possible if you could share with me how this was achieved using deep GTAV and script hook v because I can only generate the frontal view images with annotations ?

**Comment by ndrplz** [comment]
Hi @AmalMak, thank you for your interest.

We're currently still working on this acquisition framework. We plan to release all the code as soon as we get to a more stable version.

However, basically what happens is the following.

You create two cameras with `CAM::CREATE_CAM("DEFAULT_SCRIPTED_CAMERA", TRUE);`

For each of the two cameras, you set the FOV, rotation and so on as you like. Then at each game step you just switch camera with `CAM::SET_CAM_ACTIVE(<one of your cameras>, TRUE);`

PS: If the camera is not rendered immediately you can try to force it with `CAM::RENDER_SCRIPT_CAMS(TRUE, FALSE, 0, TRUE, TRUE);`

**Comment by AmalMak** [comment]
Thanks @ndrplz for your reply. I will try this out and see how it will work.
