### ISSUE TITLE
Datafile column labels

### ISSUE THREAD

**Issue by ldaehler** [ndrplz/surround_vehicles_awareness#5]
Hi thanks for making this project and dataset available. 

I was wondering if you had the names of the columns for the unfiltered bboxes.txt files. It looks like there's some more information in the file that could be useful and I'd like to use it if possible. 

Thanks!

**Comment by ndrplz** [comment]
Not sure why this was never answered. Sorry about that. Unfortunately we don't have that information readily available now.
